import {marked} from './vendor/marked.js';
export const blockLabels={paragraph:'문단',heading:'제목 1',subheading:'제목 2',h3:'제목 3',bullet:'글머리 목록',ordered:'번호 목록',task:'할 일',quote:'인용',callout:'콜아웃',code:'코드',table:'표',toggle:'접기',divider:'구분선',link:'웹 링크',page:'기록 링크',math:'수학 수식',columns:'2열 배치',toc:'목차',file:'첨부 블록',synced:'공유 블록',database:'연결 데이터베이스',embed:'웹 북마크'};
export function specialBlock(type,value={}){return '```pkos-'+type+'\n'+JSON.stringify(value)+'\n```\n\n';}
export function readSpecial(raw){const match=String(raw).trim().match(/^(`{3,}|~{3,})pkos-([a-z]+)\s*\n([\s\S]*?)\n\1$/);if(!match)return null;try{const value=JSON.parse(match[3]);if(!value||typeof value!=='object'||Array.isArray(value))return null;return {type:match[2],value};}catch{return null;}}
export function splitBlocks(markdown){
 const blocks=[];let prefix='';for(const token of marked.lexer(markdown)){if(token.type==='space'){if(blocks.length)blocks.at(-1).raw+=token.raw;else prefix+=token.raw;continue;}const raw=prefix+token.raw;blocks.push({id:crypto.randomUUID(),type:readSpecial(raw)?.type||token.type,raw});prefix='';}
 if(prefix)blocks.push({id:crypto.randomUUID(),type:'paragraph',raw:prefix});return blocks.map(b=>b.raw).join('')===markdown?blocks:[{id:crypto.randomUUID(),type:'raw',raw:markdown}];
}
export const joinBlocks=blocks=>blocks.map(b=>b.raw).join('');
export const blockTemplates={paragraph:'새 문단\n\n',heading:'# 제목\n\n',subheading:'## 소제목\n\n',h3:'### 작은 제목\n\n',bullet:'- 목록 항목\n\n',ordered:'1. 목록 항목\n\n',task:'- [ ] 할 일\n\n',quote:'> 인용문\n\n',callout:specialBlock('callout',{icon:'💡',color:'yellow',body:'기억할 내용\n'}),code:'```text\n코드\n```\n\n',table:'| 항목 | 내용 |\n| --- | --- |\n| 이름 | 값 |\n\n',toggle:specialBlock('toggle',{title:'펼쳐 보기',body:'내용\n'}),divider:'---\n\n',link:'[링크 이름](https://example.com)\n\n',page:'[[연결할 기록 제목]]\n\n',math:specialBlock('math',{expression:'E = mc^2'}),columns:specialBlock('columns',{columns:['왼쪽 내용\n','오른쪽 내용\n']}),toc:specialBlock('toc'),file:specialBlock('file',{id:'',caption:''}),synced:specialBlock('synced',{id:''}),database:specialBlock('database',{id:'',view:''}),embed:specialBlock('embed',{url:'',title:''})};
export function moveBlocks(blocks,ids,target,after=false){const moving=blocks.filter(b=>ids.includes(b.id));if(ids.includes(target)||!moving.length)return blocks;const rest=blocks.filter(b=>!ids.includes(b.id)),index=rest.findIndex(b=>b.id===target);if(index<0)return blocks;rest.splice(index+(after?1:0),0,...moving);return rest;}
export function blockReferenceIds(body,depth=0){if(depth>8||!/(?:`{3,}|~{3,})pkos-/.test(body))return [];const ids=[];for(const block of splitBlocks(body)){const s=readSpecial(block.raw);if(!s)continue;if(['database','synced'].includes(s.type)&&typeof s.value.id==='string')ids.push(s.value.id);if(typeof s.value.body==='string')ids.push(...blockReferenceIds(s.value.body,depth+1));if(Array.isArray(s.value.columns))for(const body of s.value.columns)if(typeof body==='string')ids.push(...blockReferenceIds(body,depth+1));}return ids;}
export function renameBlockReferences(body,noteIds,assetIds=new Map(),depth=0){if(depth>8||!/(?:`{3,}|~{3,})pkos-/.test(body))return body;return splitBlocks(body).map(block=>{const s=readSpecial(block.raw);if(!s)return block.raw;const v=s.value,before=JSON.stringify(v);if(['database','synced'].includes(s.type)&&typeof v.id==='string')v.id=noteIds.get(v.id)||v.id;if(s.type==='file'&&typeof v.id==='string')v.id=assetIds.get(v.id)||v.id;if(typeof v.body==='string')v.body=renameBlockReferences(v.body,noteIds,assetIds,depth+1);if(Array.isArray(v.columns))v.columns=v.columns.map(x=>typeof x==='string'?renameBlockReferences(x,noteIds,assetIds,depth+1):x);return before===JSON.stringify(v)?block.raw:specialBlock(s.type,v);}).join('');}
