import {marked} from './vendor/marked.js';
import DOMPurify from './vendor/purify.js';
import {splitBlocks,joinBlocks,blockTemplates,blockLabels,specialBlock,readSpecial,moveBlocks} from './block-model.js';
import {esc} from './core.js';
const safeInline=raw=>DOMPurify.sanitize(marked.parse(raw),{ALLOWED_TAGS:['p','h1','h2','h3','h4','h5','h6','strong','em','del','s','u','code','a','br','blockquote','ul','ol','li','input'],ALLOWED_ATTR:['href','type','checked','disabled','start'],ALLOW_DATA_ATTR:false});
const textEscape=s=>s.replace(/([\\`*_\[\]<>])/g,'\\$1');
export function editableMarkdown(node){
 const children=n=>[...n.childNodes].map(walk).join('');
 function walk(n){if(n.nodeType===3)return textEscape(n.textContent.replace(/\u00a0/g,' '));if(n.nodeType!==1)return '';const content=children(n);switch(n.tagName){case 'BR':return '\n';case 'STRONG':case 'B':return '**'+content+'**';case 'EM':case 'I':return '*'+content+'*';case 'DEL':case 'S':return '~~'+content+'~~';case 'U':return '<u>'+content+'</u>';case 'CODE':return '`'+n.textContent.replaceAll('`','\\`')+'`';case 'A':{const href=n.getAttribute('href')||'';return /^(https?:|mailto:|#)/i.test(href)?'['+content+']('+href.replaceAll(')','%29')+')':content;}case 'INPUT':return '';case 'UL':case 'OL':return [...n.children].filter(c=>c.tagName==='LI').map((li,i)=>{const checkbox=[...li.children].find(x=>x.tagName==='INPUT'),nested=[...li.children].filter(x=>['UL','OL'].includes(x.tagName));const clone=li.cloneNode(true);clone.querySelectorAll('ul,ol,input').forEach(x=>x.remove());const prefix=n.tagName==='OL'?(Number(n.getAttribute('start')||1)+i)+'. ':checkbox?(checkbox.checked?'- [x] ':'- [ ] '):'- ';return prefix+children(clone).trim()+(nested.length?'\n'+nested.map(walk).join('\n').split('\n').map(l=>'  '+l).join('\n'):'');}).join('\n');case 'P':case 'DIV':return content+'\n';default:return content;}}
 return children(node).replace(/\n{3,}/g,'\n\n').trimEnd();
}
const tokenOf=b=>marked.lexer(b.raw).find(t=>t.type!=='space')||{type:'paragraph',text:''};
function richKind(b){if(readSpecial(b.raw))return '';const t=tokenOf(b);return ['paragraph','heading','blockquote','list'].includes(t?.type)&&!b.raw.includes('<')&&!b.raw.includes('![')?t.type:'';}
export function mountBlocks(textarea,api={}){
 if(!textarea||textarea.dataset.blocksMounted)return;textarea.dataset.blocksMounted='1';const depth=api.depth||0,editorId=crypto.randomUUID(),toolbar=textarea.closest('.editor-page')?.querySelector('.format-bar')||api.toolbar||textarea.parentElement;
 let blocks=splitBlocks(textarea.value),active=false,rawMode=new Set(),selected=new Set(),history=[],future=[],focused='',typingCheckpoint='',publishing=false,dragIds=[],range=null;
 const root=document.createElement('section');root.className='block-editor';root.hidden=true;root.dataset.editorId=editorId;
 const toggle=document.createElement('button');toggle.type='button';toggle.textContent='블록으로 편집';toggle.className='format';textarea.before(root);toolbar.append(toggle);
 const ensureBoundaries=()=>blocks.forEach((b,i)=>{if(i<blocks.length-1&&!b.raw.endsWith('\n\n'))b.raw=b.raw.trimEnd()+'\n\n';});
 const snapshot=()=>{history.push(structuredClone(blocks));if(history.length>50)history.shift();future=[];};
 const publish=()=>{publishing=true;textarea.value=joinBlocks(blocks);textarea.dispatchEvent(new Event('input',{bubbles:true}));publishing=false;};
 const commit=fn=>{snapshot();fn();ensureBoundaries();typingCheckpoint='';publish();render();};
 function update(b,raw){if(typingCheckpoint!==b.id){snapshot();typingCheckpoint=b.id;}b.raw=raw;publish();}
 function chosen(fallback){const ids=selected.size?[...selected]:fallback?[fallback]:focused?[focused]:[];return blocks.filter(b=>ids.includes(b.id));}
 function add(type,index=blocks.length){commit(()=>{const b={id:crypto.randomUUID(),type,raw:blockTemplates[type]||blockTemplates.paragraph};blocks.splice(index,0,b);focused=b.id;selected.clear();});focusBlock(focused);}
 function focusBlock(id){const row=root.querySelector('[data-block-id="'+id+'"]');(row?.querySelector('[contenteditable=true]')||row?.querySelector('textarea'))?.focus();}
 function render(){root.innerHTML=`<div class="blocks-toolbar"><label><input type="checkbox" data-block-all ${blocks.length&&selected.size===blocks.length?'checked':''}>${selected.size?selected.size+'개 선택':'블록 선택'}</label><button type="button" data-block-action="undo" ${history.length?'':'disabled'} aria-label="블록 실행 취소">↶</button><button type="button" data-block-action="redo" ${future.length?'':'disabled'} aria-label="블록 다시 실행">↷</button><button type="button" data-block-action="group-columns">2열로 묶기</button><button type="button" data-block-action="group-toggle">접기 안에 묶기</button>${selected.size?'<button type="button" data-block-action="duplicate">선택 복제</button><button type="button" data-block-action="remove">선택 삭제</button>':''}</div><div class="block-items">${blocks.map((b,i)=>`<section class="block-row ${selected.has(b.id)?'is-selected':''}" data-block-id="${b.id}"><div class="block-controls"><button type="button" class="block-grip" draggable="true" data-drag-block="${b.id}" title="끌어서 이동">⠿</button><input type="checkbox" data-block-select="${b.id}" ${selected.has(b.id)?'checked':''} aria-label="블록 ${i+1} 선택"><span>${i+1}</span><select data-block-convert aria-label="블록 ${i+1} 종류">${['paragraph','heading','subheading','h3','bullet','ordered','task','quote','code'].map(k=>`<option value="${k}" ${kindFor(b)===k?'selected':''}>${blockLabels[k]}</option>`).join('')}<option value="custom" ${!['paragraph','heading','subheading','h3','bullet','ordered','task','quote','code'].includes(kindFor(b))?'selected':''}>${esc(blockLabels[kindFor(b)]||'원문')}</option></select><button type="button" data-block-action="up" ${i===0?'disabled':''} aria-label="위로 이동">↑</button><button type="button" data-block-action="down" ${i===blocks.length-1?'disabled':''} aria-label="아래로 이동">↓</button><details class="block-menu"><summary aria-label="블록 메뉴">•••</summary><div><button type="button" data-block-action="after">아래에 추가</button><button type="button" data-block-action="indent">하위로 넣기</button>${api.onLift?'<button type="button" data-block-action="lift">상위로 꺼내기</button>':''}<button type="button" data-block-action="duplicate">복제</button><button type="button" data-block-action="raw">${rawMode.has(b.id)?'화면으로 편집':'Markdown 원문'}</button>${api.createNote?'<button type="button" data-block-action="share">공유 블록으로 만들기</button>':''}<button type="button" data-block-action="remove">삭제</button></div></details></div><div class="block-content"></div></section>`).join('')}</div><div class="block-add"><select aria-label="새 블록 종류">${Object.entries(blockLabels).filter(([k])=>depth<5||!['columns','toggle','callout'].includes(k)).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select><button type="button" data-block-action="add">＋ 블록 추가</button></div>`;
  for(const b of blocks){const row=root.querySelector('[data-block-id="'+b.id+'"]'),box=row.querySelector('.block-content');if(rawMode.has(b.id)){rawEditor(box,b);continue;}const special=readSpecial(b.raw);if(special){specialEditor(box,b,special);continue;}const t=tokenOf(b);if(t?.type==='table'){tableEditor(box,b,t);continue;}if(richKind(b)){const editable=document.createElement('div');editable.className='block-rich prose';editable.contentEditable='true';editable.setAttribute('role','textbox');editable.setAttribute('aria-label','블록 '+(blocks.indexOf(b)+1)+' 내용');editable.spellcheck=false;editable.innerHTML=safeInline(b.raw);editable.querySelectorAll('input').forEach(x=>{x.disabled=false;x.setAttribute('contenteditable','false');});box.append(editable);editable.addEventListener('input',()=>{let raw=editableMarkdown(editable);if(t.type==='heading')raw='#'.repeat(t.depth)+' '+raw;if(t.type==='blockquote')raw=raw.split('\n').map(s=>'> '+s).join('\n');update(b,raw+'\n\n');});editable.addEventListener('change',()=>editable.dispatchEvent(new Event('input')));editable.addEventListener('keydown',e=>richKey(e,b,editable));editable.addEventListener('paste',e=>{e.preventDefault();const text=e.clipboardData.getData('text/plain');document.execCommand('insertText',false,text);});}
   else if(t?.type==='hr'){box.innerHTML='<hr>';}else rawEditor(box,b);
  }
 }
 function rawEditor(box,b){const input=document.createElement('textarea');input.className='block-raw';input.value=b.raw;input.setAttribute('aria-label','블록 '+(blocks.indexOf(b)+1)+' Markdown');input.spellcheck=false;input.oninput=()=>update(b,input.value);box.append(input);}
 function kindFor(b){const special=readSpecial(b.raw);if(special)return special.type;const t=tokenOf(b);return t?.type==='heading'?['','heading','subheading','h3'][t.depth]||'heading':t?.type==='list'?t.items.some(x=>x.task)?'task':t.ordered?'ordered':'bullet':t?.type==='blockquote'?'quote':t?.type==='hr'?'divider':t?.type||'paragraph';}
 function richKey(e,b,editor){if(e.isComposing)return;focused=b.id;if(e.key==='/'&&editor.textContent.trim()===''){e.preventDefault();commands(b.id);return;}if((e.ctrlKey||e.metaKey)&&['b','i','u'].includes(e.key.toLowerCase())){e.preventDefault();document.execCommand({b:'bold',i:'italic',u:'underline'}[e.key.toLowerCase()]);return;}if(e.key==='Tab'){const selection=getSelection(),li=selection?.anchorNode?.parentElement?.closest('li');if(li&&editor.contains(li)){e.preventDefault();const list=li.parentElement,anchor=selection.anchorNode,anchorOffset=selection.anchorOffset,focus=selection.focusNode,focusOffset=selection.focusOffset;if(e.shiftKey){const parent=list.parentElement?.closest('li');if(parent){parent.after(li);if(!list.children.length)list.remove();}}else{const previous=li.previousElementSibling;if(previous){let nested=[...previous.children].find(n=>n.tagName===list.tagName);if(!nested){nested=document.createElement(list.tagName);previous.append(nested);}nested.append(li);}}try{selection.setBaseAndExtent(anchor,anchorOffset,focus,focusOffset);}catch{}editor.dispatchEvent(new Event('input'));return;}}
  if(e.key==='Enter'&&!e.shiftKey&&['paragraph','heading','blockquote'].includes(richKind(b))){e.preventDefault();const sel=getSelection();if(!sel?.rangeCount)return;const selectedRange=sel.getRangeAt(0);if(!editor.contains(selectedRange.commonAncestorContainer))return;selectedRange.deleteContents();const after=document.createRange();after.selectNodeContents(editor);after.setStart(selectedRange.startContainer,selectedRange.startOffset);const remainder=document.createElement('div');remainder.append(after.extractContents());let head=editableMarkdown(editor),tail=editableMarkdown(remainder);const token=tokenOf(b);if(token.type==='heading')head='#'.repeat(token.depth)+' '+head;if(token.type==='blockquote')head='> '+head;commit(()=>{b.raw=head+'\n\n';const next={id:crypto.randomUUID(),type:'paragraph',raw:(tail||'')+'\n\n'};blocks.splice(blocks.indexOf(b)+1,0,next);focused=next.id;});focusBlock(focused);}
 }
 function commands(id){root.querySelector('.block-commands')?.remove();const row=root.querySelector('[data-block-id="'+id+'"]'),menu=document.createElement('div');menu.className='block-commands';menu.innerHTML='<input type="search" aria-label="블록 명령 찾기" placeholder="블록 종류 찾기"><div></div>';row.append(menu);const paint=()=>{const q=menu.querySelector('input').value.toLowerCase();menu.querySelector('div').innerHTML=Object.entries(blockLabels).filter(([k,v])=>(k+' '+v).toLowerCase().includes(q)).map(([k,v])=>`<button type="button" data-command="${k}">${v}</button>`).join('');};menu.querySelector('input').oninput=paint;menu.onclick=e=>{const type=e.target.closest('[data-command]')?.dataset.command;if(!type)return;const b=blocks.find(b=>b.id===id);commit(()=>{b.raw=blockTemplates[type];b.type=type;});};menu.onkeydown=e=>{if(e.key==='Escape'){menu.remove();focusBlock(id);}};paint();menu.querySelector('input').focus();}
 function tableEditor(box,b,t){const rows=[t.header.map(x=>x.text),...t.rows.map(r=>r.map(x=>x.text))];const paint=()=>{box.innerHTML=`<div class="block-table-scroll"><table>${rows.map((r,i)=>'<tr>'+r.map((v,j)=>`<${i?'td':'th'}><input value="${esc(v)}" data-table-cell="${i},${j}" aria-label="표 ${i+1}행 ${j+1}열"></${i?'td':'th'}>`).join('')+`<td><button type="button" data-table-remove-row="${i}" ${i===0?'disabled':''} aria-label="표 행 삭제">−</button></td></tr>`).join('')}</table></div><div class="block-table-tools"><button type="button" data-table-add-row>행 추가</button><button type="button" data-table-add-col>열 추가</button><button type="button" data-table-remove-col>마지막 열 삭제</button></div>`;};const publishTable=()=>{const cell=v=>String(v).replace(/\r?\n/g,'<br>').replaceAll('|','\\|');update(b,rows.map((r,i)=>(i===1?'| '+rows[0].map(()=> '---').join(' | ')+' |\n':'')+'| '+r.map(cell).join(' | ')+' |').join('\n')+(rows.length===1?'\n| '+rows[0].map(()=> '---').join(' | ')+' |':'')+'\n\n');};box.oninput=e=>{if(e.target.dataset.tableCell){const [i,j]=e.target.dataset.tableCell.split(',').map(Number);rows[i][j]=e.target.value;publishTable();}};box.onclick=e=>{if(e.target.hasAttribute('data-table-add-row')&&rows.length<200)rows.push(rows[0].map(()=>''));else if(e.target.hasAttribute('data-table-add-col')&&rows[0].length<30)rows.forEach(r=>r.push(''));else if(e.target.hasAttribute('data-table-remove-col')&&rows[0].length>1)rows.forEach(r=>r.pop());else if(e.target.dataset.tableRemoveRow)rows.splice(Number(e.target.dataset.tableRemoveRow),1);else return;publishTable();paint();};paint();}
 function specialEditor(box,b,s){const v=s.value;const write=()=>update(b,specialBlock(s.type,v));
  const nested=(parent,body,onChange)=>{const section=document.createElement('section');section.className='editor-page block-nested';section.innerHTML='<div class="format-bar"></div><textarea aria-label="중첩 블록 본문"></textarea>';const t=section.querySelector('textarea');t.value=body;parent.append(section);t.addEventListener('input',e=>{e.stopPropagation();onChange(t.value);write();});if(depth<6)mountBlocks(t,{...api,depth:depth+1,active:true,onLift:raw=>{commit(()=>{blocks.splice(blocks.indexOf(b)+1,0,{id:crypto.randomUUID(),type:'paragraph',raw});});}});};
  if(s.type==='columns'&&Array.isArray(v.columns)&&v.columns.every(x=>typeof x==='string')&&v.columns.length<=4){box.className+=' block-column-editor';v.columns.forEach((body,i)=>nested(box,body,body=>v.columns[i]=body));}
  else if(['toggle','callout'].includes(s.type)&&typeof v.body==='string'){box.innerHTML=s.type==='toggle'?`<label>접기 제목<input data-special-title value="${esc(v.title||'')}"></label>`:`<div class="block-callout-tools"><input data-special-icon aria-label="아이콘" maxlength="10" value="${esc(v.icon||'💡')}"><select data-special-color aria-label="콜아웃 색">${['gray','yellow','blue','green','pink'].map(k=>`<option ${v.color===k?'selected':''}>${k}</option>`).join('')}</select></div>`;box.querySelector('[data-special-title]')?.addEventListener('input',e=>{v.title=e.target.value;write();});box.querySelector('[data-special-icon]')?.addEventListener('input',e=>{v.icon=e.target.value;write();});box.querySelector('[data-special-color]')?.addEventListener('change',e=>{v.color=e.target.value;write();});nested(box,v.body,body=>v.body=body);}
  else if(s.type==='math'){box.innerHTML=`<label>LaTeX 수식<textarea data-math-expression>${esc(v.expression||'')}</textarea></label><div class="block-math-preview"></div>`;const preview=async()=>{try{const {default:katex}=await import('./vendor/katex/katex.mjs');katex.render(v.expression||'',box.querySelector('.block-math-preview'),{displayMode:true,throwOnError:false,trust:false,maxExpand:1000});}catch{}};box.querySelector('textarea').oninput=e=>{v.expression=e.target.value;write();void preview();};void preview();}
  else if(s.type==='toc'){box.innerHTML='<p class="hint">읽기 화면에 제목 1·2·3의 목차가 표시됩니다.</p>';}
  else if(['synced','database','file'].includes(s.type)){const items=s.type==='file'?(api.assets||[]).map(a=>({id:a.id,title:a.name})):(api.notes||[]).filter(n=>!n.deleted&&n.id!==api.noteId&&(s.type!=='database'||n.database));box.innerHTML=`<label>${s.type==='file'?'첨부 파일':s.type==='database'?'원본 데이터베이스':'함께 사용할 원본 기록'}<select data-reference><option value="">선택</option>${items.map(n=>`<option value="${esc(n.id)}" ${v.id===n.id?'selected':''}>${esc(n.title||'제목 없음')}</option>`).join('')}</select></label>${s.type==='file'?`<label>설명<input data-caption value="${esc(v.caption||'')}"></label>`:''}<p class="hint">${s.type==='synced'?'원본 기록을 고치면 이 기록에서도 같은 내용을 봅니다.':s.type==='database'?'원본 데이터베이스의 값을 이 자리에서도 수정할 수 있습니다.':'기록에 먼저 첨부한 원본을 본문에 배치합니다.'}</p>`;box.querySelector('[data-reference]').onchange=e=>{v.id=e.target.value;write();};box.querySelector('[data-caption]')?.addEventListener('input',e=>{v.caption=e.target.value;write();});}
  else if(s.type==='embed'){box.innerHTML=`<label>웹 주소<input type="url" value="${esc(v.url||'')}" data-bookmark-url></label><label>이름<input value="${esc(v.title||'')}" data-bookmark-title></label>`;box.querySelector('[data-bookmark-url]').oninput=e=>{v.url=e.target.value;write();};box.querySelector('[data-bookmark-title]').oninput=e=>{v.title=e.target.value;write();};}
  else rawEditor(box,b);
 }
 root.addEventListener('focusin',e=>{const row=e.target.closest('[data-block-id]');if(row&&row.closest('[data-editor-id]')===root){focused=row.dataset.blockId;const sel=getSelection();if(sel?.rangeCount)range=sel.getRangeAt(0).cloneRange();}});
 root.addEventListener('mouseup',()=>{const sel=getSelection();if(sel?.rangeCount&&root.contains(sel.anchorNode))range=sel.getRangeAt(0).cloneRange();});
 root.addEventListener('change',e=>{if(e.target.closest('[data-editor-id]')!==root)return;if(e.target.dataset.blockSelect){e.target.checked?selected.add(e.target.dataset.blockSelect):selected.delete(e.target.dataset.blockSelect);render();}else if(e.target.hasAttribute('data-block-all')){selected=e.target.checked?new Set(blocks.map(b=>b.id)):new Set();render();}else if(e.target.hasAttribute('data-block-convert')&&e.target.value!=='custom'){const b=blocks.find(b=>b.id===e.target.closest('[data-block-id]').dataset.blockId),type=e.target.value,t=tokenOf(b);let text=t?.type==='list'?t.items.map(i=>i.text).join('\n'):t?.text||b.raw.trim();commit(()=>{b.raw=type==='paragraph'?text+'\n\n':type==='heading'?'# '+text+'\n\n':type==='subheading'?'## '+text+'\n\n':type==='h3'?'### '+text+'\n\n':type==='quote'?text.split('\n').map(l=>'> '+l).join('\n')+'\n\n':type==='code'?'```text\n'+text+'\n```\n\n':text.split('\n').map((l,i)=>(type==='ordered'?(i+1)+'. ':type==='task'?'- [ ] ':'- ')+l).join('\n')+'\n\n';b.type=type;});}});
 root.addEventListener('click',async e=>{const button=e.target.closest('[data-block-action]');if(!button||button.closest('[data-editor-id]')!==root)return;e.stopPropagation();const action=button.dataset.blockAction,id=button.closest('[data-block-id]')?.dataset.blockId||focused,b=blocks.find(b=>b.id===id),index=blocks.indexOf(b),picked=chosen(id);
  if(action==='add'){add(root.querySelector(':scope > .block-add select').value);return;}if(action==='after'){add('paragraph',index+1);return;}
  if(action==='undo'||action==='redo'){const from=action==='undo'?history:future,to=action==='undo'?future:history;if(from.length){to.push(structuredClone(blocks));blocks=from.pop();selected.clear();typingCheckpoint='';publish();render();}return;}
  if(action==='raw'){rawMode.has(id)?rawMode.delete(id):rawMode.add(id);render();return;}
  if(action==='share'&&b&&api.createNote){try{const name=prompt('공유 블록 이름','공유 내용');if(!name)return;const note=await api.createNote({title:name,body:b.raw});api.notes=[...(api.notes||[]),note];commit(()=>b.raw=specialBlock('synced',{id:note.id}));}catch(e){api.toast?.(e.message);}return;}
  if(action==='lift'&&api.onLift&&b){const raw=b.raw;commit(()=>blocks.splice(index,1));api.onLift(raw);return;}
  commit(()=>{if(action==='remove'){const ids=new Set(picked.map(b=>b.id));blocks=blocks.filter(b=>!ids.has(b.id));selected.clear();}if(action==='duplicate'){for(const item of picked){const i=blocks.indexOf(item);blocks.splice(i+1,0,{...item,id:crypto.randomUUID()});}}if(action==='up'&&index>0)[blocks[index-1],blocks[index]]=[blocks[index],blocks[index-1]];if(action==='down'&&index>=0&&index<blocks.length-1)[blocks[index+1],blocks[index]]=[blocks[index],blocks[index+1]];
   if(action==='indent'&&index>0){const previous=blocks[index-1],s=readSpecial(previous.raw);if(s&&['toggle','callout'].includes(s.type)){s.value.body+=b.raw;previous.raw=specialBlock(s.type,s.value);}else previous.raw=specialBlock('toggle',{title:'묶음',body:previous.raw+b.raw});blocks.splice(index,1);}
   if(['group-columns','group-toggle'].includes(action)&&picked.length){const ids=new Set(picked.map(b=>b.id)),first=blocks.findIndex(b=>ids.has(b.id)),body=joinBlocks(picked);blocks=blocks.filter(b=>!ids.has(b.id));blocks.splice(first,0,{id:crypto.randomUUID(),type:action==='group-columns'?'columns':'toggle',raw:action==='group-columns'?specialBlock('columns',{columns:picked.length>1?[joinBlocks(picked.slice(0,Math.ceil(picked.length/2))),joinBlocks(picked.slice(Math.ceil(picked.length/2)))]:[body,'']}):specialBlock('toggle',{title:'펼쳐 보기',body})});selected.clear();}
  });
 });
 root.addEventListener('dragstart',e=>{const grip=e.target.closest('[data-drag-block]');if(!grip||grip.closest('[data-editor-id]')!==root)return;e.stopPropagation();dragIds=selected.has(grip.dataset.dragBlock)?[...selected]:[grip.dataset.dragBlock];e.dataTransfer.setData('application/x-pkos-blocks',JSON.stringify({editorId,ids:dragIds}));e.dataTransfer.effectAllowed='move';});
 root.addEventListener('dragover',e=>{const row=e.target.closest('[data-block-id]');if(dragIds.length&&row?.closest('[data-editor-id]')===root){e.preventDefault();e.stopPropagation();}});
 root.addEventListener('drop',e=>{const row=e.target.closest('[data-block-id]');if(!dragIds.length||row?.closest('[data-editor-id]')!==root)return;e.preventDefault();e.stopPropagation();const after=e.clientY>row.getBoundingClientRect().top+row.getBoundingClientRect().height/2;commit(()=>blocks=moveBlocks(blocks,dragIds,row.dataset.blockId,after));dragIds=[];});root.addEventListener('dragend',()=>dragIds=[]);
 toolbar.addEventListener('mousedown',e=>{if(active&&e.target.closest('[data-action]')&&['bold','italic','heading','bullet','quote'].includes(e.target.closest('[data-action]').dataset.action))e.preventDefault();});
 toolbar.addEventListener('click',e=>{if(!active)return;const action=e.target.closest('[data-action]')?.dataset.action;if(!['bold','italic','heading','bullet','quote'].includes(action))return;e.stopPropagation();const editor=root.querySelector('[data-block-id="'+focused+'"] .block-rich');if(!editor)return;editor.focus();if(range&&editor.contains(range.commonAncestorContainer)){const s=getSelection();s.removeAllRanges();s.addRange(range);}if(action==='bold'||action==='italic')document.execCommand(action);else{const select=editor.closest('.block-row').querySelector('[data-block-convert]');select.value={heading:'subheading',bullet:'bullet',quote:'quote'}[action];select.dispatchEvent(new Event('change',{bubbles:true}));}});
 toggle.onclick=()=>{active=!active;root.hidden=!active;textarea.hidden=active;toggle.textContent=active?'Markdown으로 편집':'블록으로 편집';if(active){blocks=splitBlocks(textarea.value);render();}};
 textarea.addEventListener('input',()=>{if(active&&!publishing){blocks=splitBlocks(textarea.value);render();}});
 if(api.active)toggle.click();return {root,get:()=>joinBlocks(blocks)};
}
