import {renameBlockReferences,blockReferenceIds} from './block-model.js';
import {evaluateFormula} from './formula.js';
export const propertyTypes={text:'텍스트',number:'숫자',select:'선택',status:'상태',multi:'다중 선택',date:'날짜',checkbox:'체크',url:'URL',email:'이메일',phone:'전화',files:'파일·미디어',person:'담당자',relation:'관계',formula:'수식',rollup:'롤업 집계',created:'생성 시간',updated:'수정 시간',id:'고유 ID',button:'버튼'};
export const viewTypes={table:'표',board:'보드',calendar:'달력',list:'목록',gallery:'갤러리',timeline:'타임라인',chart:'차트',form:'입력 폼'};
export const aggregations={count:'개수',countValues:'값이 있는 개수',empty:'빈 값 개수',unique:'고유 값 개수',sum:'합계',average:'평균',min:'최솟값',max:'최댓값',checked:'체크 수',percentChecked:'체크 비율',earliest:'가장 이른 날짜',latest:'가장 늦은 날짜',show:'원래 값',uniqueValues:'고유 값'};
export const filterOperators={contains:'포함',notContains:'포함하지 않음',eq:'같음',neq:'다름',empty:'비어 있음',notEmpty:'비어 있지 않음',gt:'초과 / 이후',gte:'이상',lt:'미만 / 이전',lte:'이하',checked:'체크됨',unchecked:'체크 안 됨',within:'오늘부터 N일 이내'};
export const validId=id=>typeof id==='string'&&/^[a-zA-Z0-9_-]{1,128}$/.test(id)&&!['__proto__','prototype','constructor'].includes(id);
const isValue=v=>typeof v==='string'||typeof v==='boolean'||typeof v==='number'&&Number.isFinite(v)||Array.isArray(v)&&v.length<=10000&&v.every(x=>typeof x==='string');
const cellObject=c=>c&&typeof c==='object'&&!Array.isArray(c)&&Object.entries(c).every(([k,v])=>validId(k)&&isValue(v));
const string=(v,max=2000000)=>typeof v==='string'&&v.length<=max;
const check=(condition,message)=>{if(!condition)throw Error(message);};
export function validateFilter(filter,depth=0){check(filter&&typeof filter==='object'&&!Array.isArray(filter)&&depth<=5,'필터 형식이 올바르지 않습니다.');if(filter.rules){check(['and','or'].includes(filter.mode)&&Array.isArray(filter.rules)&&filter.rules.length<=30,'필터 그룹을 확인하세요.');filter.rules.forEach(f=>validateFilter(f,depth+1));}else check(validId(filter.column)&&Object.hasOwn(filterOperators,filter.op)&&isValue(filter.value??''),'필터 조건을 확인하세요.');return filter;}
export function parseDatabase(text){
 const d=typeof text==='string'?JSON.parse(text):text;
 check(d&&d.version===1&&Array.isArray(d.columns)&&d.columns.length>0&&d.columns.length<=60&&Array.isArray(d.rows)&&d.rows.length<=10000,'데이터베이스 형식을 확인하세요.');
 const ids=new Set();for(const c of d.columns){check(c&&validId(c.id)&&!ids.has(c.id)&&string(c.name,100000)&&Object.hasOwn(propertyTypes,c.type),'속성이 손상되었습니다.');ids.add(c.id);
  for(const field of ['expression','source','target','targetColumn','inverseColumn','buttonLabel','buttonColumn'])if(c[field]!==undefined)check(string(c[field],16000),'속성 설정을 확인하세요.');
  if(c.options!==undefined)check(Array.isArray(c.options)&&c.options.length<=300&&c.options.every(x=>string(x,100000)),'선택 항목을 확인하세요.');
  if(c.aggregate!==undefined)check(Object.hasOwn(aggregations,c.aggregate),'집계 종류를 확인하세요.');if(c.buttonValue!==undefined)check(isValue(c.buttonValue),'버튼 값을 확인하세요.');
 }
 const rows=new Set();for(const r of d.rows){check(r&&validId(r.id)&&!rows.has(r.id)&&cellObject(r.cells),'행이 손상되었습니다.');rows.add(r.id);for(const k of ['body','icon','created','updated'])if(r[k]!==undefined)check(string(r[k],k==='body'?2000000:100),'행 본문이나 날짜가 손상되었습니다.');if(r.parent!==undefined)check(r.parent===''||validId(r.parent),'하위 항목 연결을 확인하세요.');}
 const byId=new Map(d.rows.map(r=>[r.id,r]));for(const r of d.rows){let p=r,seen=new Set([r.id]);while(p.parent&&byId.has(p.parent)){check(!seen.has(p.parent),'하위 항목이 서로 순환하고 있습니다.');seen.add(p.parent);p=byId.get(p.parent);}}
 if(d.views!==undefined){check(Array.isArray(d.views)&&d.views.length>0&&d.views.length<=40,'보기를 확인하세요.');const seen=new Set();for(const v of d.views){check(v&&validId(v.id)&&!seen.has(v.id)&&string(v.name,100)&&Object.hasOwn(viewTypes,v.type),'보기 설정을 확인하세요.');seen.add(v.id);if(v.filters)validateFilter(v.filters);if(v.sorts)check(Array.isArray(v.sorts)&&v.sorts.length<=20&&v.sorts.every(s=>validId(s.column)&&['asc','desc'].includes(s.direction)),'정렬 설정을 확인하세요.');if(v.visible)check(Array.isArray(v.visible)&&v.visible.every(validId),'표시 속성을 확인하세요.');if(v.aggregates)check(Object.entries(v.aggregates).every(([k,a])=>validId(k)&&Object.hasOwn(aggregations,a)),'열 집계를 확인하세요.');if(v.widths)check(Object.entries(v.widths).every(([k,a])=>validId(k)&&Number.isFinite(a)&&a>=80&&a<=800),'열 너비를 확인하세요.');for(const k of ['query','group','date','endDate','chartValue','chartAggregate'])if(v[k]!==undefined)check(string(v[k],1000),'보기 설정 값이 올바르지 않습니다.');}}
 if(d.templates!==undefined){check(Array.isArray(d.templates)&&d.templates.length<=50,'템플릿을 확인하세요.');for(const t of d.templates)check(validId(t.id)&&string(t.name,100)&&cellObject(t.cells)&&string(t.body||''),'템플릿이 손상되었습니다.');}
 if(d.automations!==undefined){check(Array.isArray(d.automations)&&d.automations.length<=30,'자동화 규칙을 확인하세요.');for(const a of d.automations)check(validId(a.id)&&string(a.name,100)&&['created','changed'].includes(a.trigger)&&validId(a.column)&&isValue(a.equals??'')&&validId(a.setColumn)&&isValue(a.value??''),'자동화 규칙이 손상되었습니다.');}
 return d;
}
export function newView(name='전체',type='table'){return {id:crypto.randomUUID(),name,type,query:'',filters:{mode:'and',rules:[]},sorts:[],visible:[],group:'status',date:'date',endDate:'',aggregates:{},widths:{}};}
export function newDatabase(){const v=newView();return {version:1,columns:[{id:'title',name:'이름',type:'text'},{id:'status',name:'상태',type:'select',options:['시작 전','진행 중','완료']},{id:'date',name:'날짜',type:'date'}],rows:[],view:'table',filter:'',sort:'title',descending:false,group:'status',date:'date',views:[v],activeView:v.id,templates:[],automations:[]};}
export function prepareDatabase(value){const d=structuredClone(parseDatabase(value));if(!d.views?.length){const v=newView('전체',Object.hasOwn(viewTypes,d.view)?d.view:'table');Object.assign(v,{query:d.filter||'',sorts:d.sort?[{column:d.sort,direction:d.descending?'desc':'asc'}]:[],group:d.group||'status',date:d.date||'date'});d.views=[v];d.activeView=v.id;}d.templates??=[];d.automations??=[];return d;}
export const activeView=d=>d.views?.find(v=>v.id===d.activeView)||d.views?.[0]||{type:d.view||'table',query:d.filter||'',group:d.group||'status',date:d.date||'date',sorts:d.sort?[{column:d.sort,direction:d.descending?'desc':'asc'}]:[]};
export function formulaValue(expression,cells,columns){return evaluateFormula(expression,name=>{const c=columns.find(c=>c.id===name||c.name===name);if(!c)throw Error('속성을 찾지 못했습니다: '+name);return cells[c.id]??'';});}
const parsed=new WeakMap();
export function databasesOf(notes=[]){return notes.filter(n=>n.database&&!n.deleted).flatMap(n=>{try{let d=parsed.get(n);if(!d){d=parseDatabase(n.database);parsed.set(n,d);}return [{id:n.id,title:n.title,data:d}];}catch{return [];}});}
function resolveDatabase(id,d,ctx){if(id===ctx.noteId||id==='self')return {id:ctx.noteId||'self',data:d};return ctx.databases?.find(x=>x.id===id)||databasesOf(ctx.notes).find(x=>x.id===id);}
export function relatedRows(row,col,d,ctx={}){
 if(!col.target)return {kind:'notes',items:(Array.isArray(row.cells[col.id])?row.cells[col.id]:[]).map(id=>ctx.notes?.find(n=>n.id===id&&!n.deleted)).filter(Boolean)};
 const target=resolveDatabase(col.target,d,ctx);if(!target)return {kind:'rows',items:[]};
 const ids=Array.isArray(row.cells[col.id])?row.cells[col.id]:[];
 const items=col.inverseColumn?target.data.rows.filter(r=>Array.isArray(r.cells[col.inverseColumn])&&r.cells[col.inverseColumn].includes(row.id)):target.data.rows.filter(r=>ids.includes(r.id));
 return {kind:'rows',items,database:target};
}
export const displayValue=v=>Array.isArray(v)?v.join(', '):v===true?'✓':v===false?'':String(v??'');
export function aggregateValues(values,operation='count'){
 const filled=values.filter(v=>v!==''&&v!==null&&v!==undefined),numbers=filled.filter(v=>typeof v==='number'&&Number.isFinite(v));
 switch(operation){case 'count':return values.length;case 'countValues':return filled.length;case 'empty':return values.length-filled.length;case 'unique':return new Set(filled.map(displayValue)).size;case 'sum':return numbers.reduce((n,v)=>n+v,0);case 'average':return numbers.length?numbers.reduce((n,v)=>n+v,0)/numbers.length:0;case 'min':return numbers.length?Math.min(...numbers):'';case 'max':return numbers.length?Math.max(...numbers):'';case 'checked':return values.filter(v=>v===true).length;case 'percentChecked':return values.length?Math.round(values.filter(v=>v===true).length/values.length*10000)/100+'%':'0%';case 'earliest':return filled.map(String).filter(v=>Number.isFinite(Date.parse(v))).sort()[0]||'';case 'latest':return filled.map(String).filter(v=>Number.isFinite(Date.parse(v))).sort().at(-1)||'';case 'uniqueValues':return [...new Set(filled.flat())];case 'show':return filled.flat();default:throw Error('집계 종류를 확인하세요.');}
}
export function cellValue(row,column,database,ctx={},stack=new Set()){
 const key=(ctx.noteId||'')+':'+row.id+':'+column.id;if(stack.has(key)||stack.size>50)throw Error('수식·롤업에 순환 참조가 있습니다.');const next=new Set(stack).add(key);
 if(column.type==='formula')return evaluateFormula(column.expression||'',name=>{const c=database.columns.find(c=>c.id===name||c.name===name);if(!c)throw Error('속성 없음: '+name);return cellValue(row,c,database,ctx,next);});
 if(column.type==='rollup'){const source=database.columns.find(c=>c.id===column.source&&c.type==='relation');if(!source)return 0;const relation=relatedRows(row,source,database,ctx);if(!source.target)return aggregateValues(Array.isArray(row.cells[source.id])?row.cells[source.id]:[],column.aggregate||'count');if(!relation.database)return '';const targetCol=relation.database.data.columns.find(c=>c.id===column.targetColumn);const values=relation.items.map(r=>targetCol?cellValue(r,targetCol,relation.database.data,{...ctx,noteId:relation.database.id},next):r.id);return aggregateValues(values,column.aggregate||'count');}
 if(column.type==='created'||column.type==='updated')return row[column.type]||'';if(column.type==='id')return row.id;
 if(column.type==='relation'&&column.inverseColumn)return relatedRows(row,column,database,ctx).items.map(r=>r.id);
 return row.cells[column.id]??'';
}
export function safeCell(row,col,d,ctx){try{return cellValue(row,col,d,ctx);}catch(e){return '⚠ '+e.message;}}
export function matchesFilter(row,filter,d,ctx={}){
 if(!filter)return true;if(filter.rules){if(!filter.rules.length)return true;return filter.mode==='or'?filter.rules.some(f=>matchesFilter(row,f,d,ctx)):filter.rules.every(f=>matchesFilter(row,f,d,ctx));}
 const c=d.columns.find(c=>c.id===filter.column);if(!c)return false;const v=safeCell(row,c,d,ctx),t=filter.value??'',s=displayValue(v).toLocaleLowerCase(),value=String(t).toLocaleLowerCase();
 switch(filter.op){case 'contains':return s.includes(value);case 'notContains':return !s.includes(value);case 'eq':return Array.isArray(v)?v.includes(t):String(v)===String(t);case 'neq':return Array.isArray(v)?!v.includes(t):String(v)!==String(t);case 'empty':return v===''||v==null||Array.isArray(v)&&!v.length;case 'notEmpty':return !matchesFilter(row,{...filter,op:'empty'},d,ctx);case 'checked':return v===true;case 'unchecked':return v!==true;case 'gt':return typeof v==='number'?v>Number(t):String(v)>String(t);case 'gte':return typeof v==='number'?v>=Number(t):String(v)>=String(t);case 'lt':return typeof v==='number'?v<Number(t):String(v)<String(t);case 'lte':return typeof v==='number'?v<=Number(t):String(v)<=String(t);case 'within':{const now=new Date(),today=Date.UTC(now.getFullYear(),now.getMonth(),now.getDate());const day=(Date.parse(v)-today)/86400000;return day>=0&&day<=Number(t);}default:return false;}
}
export function visibleRows(d,ctx={}){
 const v=ctx.view||activeView(d),key=String(d.filter||v.query||'').toLocaleLowerCase();const sorts=Array.isArray(v.sorts)?v.sorts:d.sort?[{column:d.sort,direction:d.descending?'desc':'asc'}]:[];
 return d.rows.filter(r=>(!key||[r.body||'',...d.columns.map(c=>displayValue(safeCell(r,c,d,ctx)))].some(s=>s.toLocaleLowerCase().includes(key)))&&matchesFilter(r,v.filters,d,ctx)).slice().sort((a,b)=>{for(const s of sorts){const c=d.columns.find(c=>c.id===s.column);if(!c)continue;const x=safeCell(a,c,d,ctx),y=safeCell(b,c,d,ctx),n=typeof x==='number'&&typeof y==='number'?x-y:displayValue(x).localeCompare(displayValue(y),'ko',{numeric:true});if(n)return n*(s.direction==='desc'?-1:1);}return 0;});
}
export function canParent(d,id,parent){if(!parent)return true;const map=new Map(d.rows.map(r=>[r.id,r]));if(!map.has(parent))return false;const seen=new Set([id]);let p=parent;while(p){if(seen.has(p))return false;seen.add(p);p=map.get(p)?.parent;}return true;}
export function setRowValue(d,rowId,columnId,value,{trigger=true}={}){const r=d.rows.find(r=>r.id===rowId),c=d.columns.find(c=>c.id===columnId);if(!r||!c)throw Error('행이나 속성을 찾지 못했습니다.');if(!isValue(value))throw Error('저장할 값을 확인하세요.');r.cells[columnId]=value;r.updated=new Date().toISOString();if(trigger)applyRules(d,r,'changed',columnId);return r;}
export function applyRules(d,row,trigger,column){for(const a of d.automations||[]){if(a.enabled===false||a.trigger!==trigger||trigger==='changed'&&a.column!==column||trigger==='changed'&&String(row.cells[a.column]??'')!==String(a.equals??''))continue;const target=d.columns.find(c=>c.id===a.setColumn);if(target&&!['formula','rollup','created','updated','id','button'].includes(target.type))row.cells[a.setColumn]=structuredClone(a.value);}}
export function makeRow(d,templateId){const t=d.templates?.find(t=>t.id===templateId),now=new Date().toISOString(),r={id:crypto.randomUUID(),cells:structuredClone(t?.cells||{}),body:t?.body||'',created:now,updated:now};applyRules(d,r,'created');return r;}
export function databaseCSV(d,ctx={}){const quote=v=>'"'+(typeof v==='boolean'?String(v):displayValue(v)).replaceAll('"','""')+'"';return '\uFEFF'+[d.columns.map(c=>quote(c.name)).join(','),...visibleRows(d,ctx).map(r=>d.columns.map(c=>quote(safeCell(r,c,d,ctx))).join(','))].join('\r\n');}
export function parseCSV(source){const rows=[];let row=[],cell='',quoted=false;source=source.replace(/^\uFEFF/,'');for(let i=0;i<source.length;i++){const c=source[i];if(c==='"'){if(quoted&&source[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&source[i+1]==='\n')i++;row.push(cell);rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('CSV의 따옴표가 닫히지 않았습니다.');if(cell||row.length){row.push(cell);rows.push(row);}return rows;}
export function databaseMarkdown(text,ctx={}){if(!text)return '';const d=parseDatabase(text),escape=v=>displayValue(v).replaceAll('|','\\|').replace(/\r?\n/g,' ');return '\n\n## 데이터베이스\n\n| '+d.columns.map(c=>escape(c.name)).join(' | ')+' |\n| '+d.columns.map(()=>'---').join(' | ')+' |\n'+d.rows.map(r=>'| '+d.columns.map(c=>escape(safeCell(r,c,d,ctx))).join(' | ')+' |').join('\n')+d.rows.filter(r=>r.body).map(r=>'\n\n### '+String(r.cells.title||r.id)+'\n\n'+r.body).join('');}
export function remapDatabase(text,noteIds,assetIds=new Map()){if(!text)return text;const d=parseDatabase(text);for(const c of d.columns){if(c.target)c.target=noteIds.get(c.target)||c.target;if(c.type==='relation'&&!c.target)for(const r of d.rows)if(Array.isArray(r.cells[c.id]))r.cells[c.id]=r.cells[c.id].map(id=>noteIds.get(id)||id);}for(const row of d.rows){if(row.body)row.body=renameBlockReferences(row.body,noteIds,assetIds);for(const c of d.columns)if(c.type==='files'&&Array.isArray(row.cells[c.id]))row.cells[c.id]=row.cells[c.id].map(id=>assetIds.get(id)||id);}for(const t of d.templates||[]){if(t.body)t.body=renameBlockReferences(t.body,noteIds,assetIds);for(const c of d.columns)if(c.type==='files'&&Array.isArray(t.cells[c.id]))t.cells[c.id]=t.cells[c.id].map(id=>assetIds.get(id)||id);}return JSON.stringify(d);}

export function databaseReferenceIds(text){if(!text)return [];const d=parseDatabase(text),ids=[];for(const c of d.columns){if(c.type==='relation'){if(c.target&&c.target!=='self')ids.push(c.target);else if(!c.target)for(const r of [...d.rows,...(d.templates||[])])if(Array.isArray(r.cells[c.id]))ids.push(...r.cells[c.id]);}}for(const r of [...d.rows,...(d.templates||[])])if(r.body)ids.push(...blockReferenceIds(r.body));return ids;}
