import {esc,uid} from './core.js';
import {newDatabase,parseDatabase,propertyTypes,cellValue,visibleRows,databaseCSV,parseCSV} from './database-model.js';
const views={table:'표',board:'보드',calendar:'달력',list:'목록',gallery:'갤러리',timeline:'날짜 순'};
const unsettled=new Set();
export const databaseBusy=()=>unsettled.size>0||!!document.activeElement?.closest('#note-database input,#note-database select');
window.addEventListener('beforeunload',e=>{if(unsettled.size){e.preventDefault();e.returnValue='';}});
export function mountDatabase(host,{value,save,notes=[],download,toast}){
 let data=value?parseDatabase(value):newDatabase(),tail=Promise.resolve(),failed=false,month=new Date().toISOString().slice(0,7),saveTimer,generation=0;
 const status=text=>{const el=host.querySelector('[data-db-status]');if(el)el.textContent=text;};
 const persist=()=>{clearTimeout(saveTimer);const snapshot=JSON.stringify(data),own=++generation;unsettled.add(host);status('저장 중');tail=tail.then(()=>save(snapshot)).then(()=>{failed=false;if(own===generation){unsettled.delete(host);status('저장됨');}}).catch(e=>{failed=true;status('저장 실패 · 이 창에서 사본을 내려받으세요');toast(e.message);});};
 const options=(list,selected)=>list.map(([v,l])=>`<option value="${esc(v)}" ${selected===v?'selected':''}>${esc(l)}</option>`).join('');
 const input=(r,c)=>{const v=cellValue(r,c,data),attrs=`data-row="${esc(r.id)}" data-col="${esc(c.id)}" aria-label="${esc(c.name)}"`;if(c.type==='formula'||c.type==='rollup')return `<output data-computed-row="${esc(r.id)}" data-computed-col="${esc(c.id)}">${esc(v)}</output>`;if(c.type==='checkbox')return `<input type="checkbox" ${attrs} ${v?'checked':''}>`;if(c.type==='select')return `<select ${attrs}>${options([['','선택'],...(c.options||[]).map(x=>[x,x])],v)}</select>`;if(c.type==='relation')return `<button type="button" data-db="relation" data-row="${esc(r.id)}" data-col="${esc(c.id)}">${Array.isArray(v)&&v.length?esc(v.map(id=>notes.find(n=>n.id===id)?.title||'삭제된 기록').join(', ')):'기록 선택'}</button>`;return `<input ${attrs} type="${['number','date','url'].includes(c.type)?c.type:'text'}" value="${esc(Array.isArray(v)?v.join(', '):v)}" ${c.type==='number'?'step="any"':''}>`;};
 const card=r=>`<section class="db-card" data-card="${esc(r.id)}">${data.columns.map(c=>`<label>${esc(c.name)}${input(r,c)}</label>`).join('')}<button type="button" data-db="copy-row" data-id="${esc(r.id)}">복제</button><button type="button" data-db="remove-row" data-id="${esc(r.id)}">행 삭제</button></section>`;
 function render(){const rows=visibleRows(data),cols=data.columns;host.innerHTML=`<div class="db-toolbar"><label>보기<select data-db-setting="view">${options(Object.entries(views),data.view)}</select></label><label>필터<input type="search" data-db-setting="filter" value="${esc(data.filter)}" placeholder="값 찾기"></label><label>정렬<select data-db-setting="sort">${options(cols.map(c=>[c.id,c.name]),data.sort)}</select></label><label><input type="checkbox" data-db-setting="descending" ${data.descending?'checked':''}>역순</label><button type="button" data-db="column">속성 추가</button><button type="button" data-db="add">새 행</button><button type="button" data-db="csv">CSV 저장</button><button type="button" data-db="import">CSV 가져오기</button><button type="button" data-db="json">구조·내용 사본</button><span data-db-status role="status">${failed?'저장 실패':'저장됨'}</span></div><p class="hint">${rows.length}개 행 · 속성 이름을 눌러 설정합니다. 기록 연결은 여러 개를 선택할 수 있습니다.</p><div class="db-properties">${cols.map(c=>`<button type="button" data-db="edit-column" data-id="${esc(c.id)}">${esc(c.name)} · ${esc(propertyTypes[c.type])}</button>`).join('')}</div><div class="db-content"></div>`;
 const box=host.querySelector('.db-content');
 if(data.view==='table'){box.innerHTML=`<div class="db-scroll"><table><thead><tr>${cols.map(c=>`<th>${esc(c.name)}</th>`).join('')}<th>행</th></tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${input(r,c)}</td>`).join('')}<td><button type="button" data-db="copy-row" data-id="${esc(r.id)}">복제</button><button type="button" data-db="remove-row" data-id="${esc(r.id)}">삭제</button></td></tr>`).join('')}</tbody></table></div>`;}
 else if(data.view==='board'){const group=cols.find(c=>c.id===data.group)||cols.find(c=>c.type==='select')||cols[0];box.innerHTML=`<label>그룹 속성<select data-db-setting="group">${options(cols.filter(c=>!['relation','formula','rollup'].includes(c.type)).map(c=>[c.id,c.name]),group.id)}</select></label><div class="db-board">${[...new Set(['',...(group.options||[]),...rows.map(r=>String(cellValue(r,group,data)))])].map(v=>`<section><h3>${esc(v||'미지정')}</h3>${rows.filter(r=>String(cellValue(r,group,data))===v).map(card).join('')}</section>`).join('')}</div>`;}
 else if(['calendar','timeline'].includes(data.view)){const col=cols.find(c=>c.id===data.date&&c.type==='date')||cols.find(c=>c.type==='date');if(!col)box.textContent='날짜 속성을 추가하면 날짜별로 볼 수 있습니다.';else{const settings=`<label>날짜 속성<select data-db-setting="date">${options(cols.filter(c=>c.type==='date').map(c=>[c.id,c.name]),col.id)}</select></label>`;if(data.view==='calendar'){const [y,m]=month.split('-').map(Number),offset=new Date(y,m-1,1).getDay(),count=new Date(y,m,0).getDate();box.innerHTML=settings+`<div class="db-toolbar"><button type="button" data-db="month-prev">이전 달</button><strong>${month}</strong><button type="button" data-db="month-next">다음 달</button></div><div class="db-month">${['일','월','화','수','목','금','토'].map(s=>'<strong>'+s+'</strong>').join('')}${'<div></div>'.repeat(offset)}${Array.from({length:count},(_,i)=>{const date=month+'-'+String(i+1).padStart(2,'0');return `<section><strong>${i+1}</strong>${rows.filter(r=>r.cells[col.id]===date).map(r=>`<button type="button" data-db="row-detail" data-id="${esc(r.id)}">${esc(r.cells.title||'이름 없음')}</button>`).join('')}</section>`;}).join('')}</div>`;const missing=rows.filter(r=>!r.cells[col.id]);if(missing.length)box.innerHTML+='<h3>날짜 미지정</h3>'+missing.map(card).join('');}else{const groups=[...new Set(rows.map(r=>String(r.cells[col.id]||'')))].sort();box.innerHTML=settings+`<div class="db-calendar">${groups.map(day=>`<section><h3>${esc(day||'날짜 미지정')}</h3>${rows.filter(r=>String(r.cells[col.id]||'')===day).map(card).join('')}</section>`).join('')}</div>`;}}}
 else{box.classList.add(data.view==='gallery'?'db-gallery':'db-list');box.innerHTML=rows.map(card).join('');}
 }
 function editColumn(id){const c=data.columns.find(c=>c.id===id),d=document.createElement('dialog');d.className='database-property-dialog';d.innerHTML=`<h2>속성 ${c?'설정':'추가'}</h2><form><label>이름<input name="name" required maxlength="100" value="${esc(c?.name||'')}"></label><label>종류<select name="type" ${c?'disabled':''}>${options(Object.entries(propertyTypes),c?.type||'text')}</select></label><label>선택 항목 (쉼표 구분)<input name="options" value="${esc(c?.options?.join(', ')||'')}"></label><label>수식: [수량] * [단가]<input name="expression" value="${esc(c?.expression||'')}"></label><label>연결 개수를 셀 속성<select name="source">${options([['','선택'],...data.columns.filter(c=>c.type==='relation').map(c=>[c.id,c.name])],c?.source||'')}</select></label><p class="hint">수식은 숫자 사칙연산을 지원합니다. 연결 개수는 선택한 기록 수를 셉니다.</p><button type="submit">저장</button><button type="button" data-close>취소</button></form>`;document.body.append(d);d.showModal();d.querySelector('[data-close]').onclick=()=>d.close();d.onclose=()=>d.remove();d.querySelector('form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),type=c?.type||f.get('type');if(!c&&data.columns.length>=60){toast('속성은 60개까지입니다.');return;}const next={id:c?.id||uid(),name:f.get('name').trim(),type,options:String(f.get('options')).split(',').map(s=>s.trim()).filter(Boolean),expression:String(f.get('expression')),source:String(f.get('source'))};if(c)Object.assign(c,next);else data.columns.push(next);render();persist();d.close();};}
 host.addEventListener('change',e=>{const t=e.target;if(t.dataset.dbSetting){data[t.dataset.dbSetting]=t.type==='checkbox'?t.checked:t.value;render();persist();return;}if(!t.dataset.row)return;const row=data.rows.find(r=>r.id===t.dataset.row),c=data.columns.find(c=>c.id===t.dataset.col);row.cells[c.id]=c.type==='checkbox'?t.checked:c.type==='number'?(t.value===''?'':Number(t.value)):c.type==='relation'?[...t.selectedOptions].map(o=>o.value):c.type==='multi'?t.value.split(',').map(s=>s.trim()).filter(Boolean):t.value;row.updated=new Date().toISOString();persist();for(const output of host.querySelectorAll('[data-computed-row]')){const r=data.rows.find(r=>r.id===output.dataset.computedRow),c=data.columns.find(c=>c.id===output.dataset.computedCol);output.textContent=String(cellValue(r,c,data));}});
 host.addEventListener('click',async e=>{const b=e.target.closest('[data-db]');if(!b)return;const action=b.dataset.db,id=b.dataset.id;
  if(action==='month-prev'||action==='month-next'){const [y,m]=month.split('-').map(Number),date=new Date(y,m-1+(action==='month-next'?1:-1),1);month=date.getFullYear()+'-'+String(date.getMonth()+1).padStart(2,'0');render();return;}
  if(action==='row-detail'){data.filter=String(data.rows.find(r=>r.id===id)?.cells.title||'');data.view='list';render();persist();return;}
  if(action==='relation'){const row=data.rows.find(r=>r.id===b.dataset.row),col=data.columns.find(c=>c.id===b.dataset.col),selected=new Set(row.cells[col.id]||[]),dialog=document.createElement('dialog');dialog.className='database-property-dialog';dialog.innerHTML='<h2>연결할 기록</h2><input type="search" placeholder="제목 찾기" aria-label="연결할 기록 검색"><div data-options></div><button type="button" data-apply>연결 저장</button><button type="button" data-close>취소</button>';document.body.append(dialog);dialog.showModal();const paint=()=>{const query=dialog.querySelector('input').value.toLowerCase();dialog.querySelector('[data-options]').innerHTML=notes.filter(n=>!n.deleted&&n.title.toLowerCase().includes(query)).slice(0,100).map(n=>`<label><input type="checkbox" value="${esc(n.id)}" ${selected.has(n.id)?'checked':''}>${esc(n.title||'제목 없음')}</label>`).join('');};dialog.querySelector('input').oninput=paint;dialog.querySelector('[data-options]').onchange=e=>e.target.checked?selected.add(e.target.value):selected.delete(e.target.value);dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.querySelector('[data-apply]').onclick=()=>{row.cells[col.id]=[...selected];render();persist();dialog.close();};dialog.onclose=()=>dialog.remove();paint();return;}
  if(action==='column'||action==='edit-column'){editColumn(id);return;}
  if(action==='csv'){download(new Blob([databaseCSV(data)],{type:'text/csv;charset=utf-8'}),'데이터베이스.csv');return;}
  if(action==='json'){download(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),'데이터베이스.json');return;}
  if(action==='import'){const f=document.createElement('input');f.type='file';f.accept='.csv,text/csv';f.onchange=async()=>{try{if(f.files[0].size>5e6)throw Error('CSV는 5MB까지입니다.');const [headers,...rows]=parseCSV(await f.files[0].text());if(!headers||data.rows.length+rows.length>10000)throw Error('행은 10,000개까지입니다.');const columns=headers.map(h=>data.columns.find(c=>c.name===h)||{id:uid(),name:h,type:'text'});if(new Set([...data.columns,...columns].map(c=>c.id)).size>60)throw Error('속성은 60개까지입니다.');for(const c of columns)if(!data.columns.some(x=>x.id===c.id))data.columns.push(c);for(const values of rows)data.rows.push({id:uid(),cells:Object.fromEntries(columns.map((c,i)=>[c.id,c.type==='number'?Number(values[i]||0):c.type==='checkbox'?['true','1'].includes(values[i]):['relation','multi'].includes(c.type)?String(values[i]||'').split(',').filter(Boolean):values[i]||'']))});render();persist();}catch(e){toast(e.message);}};f.click();return;}
  if(action==='add'||action==='copy-row'){if(data.rows.length>=10000){toast('행은 10,000개까지입니다.');return;}const source=data.rows.find(r=>r.id===id);data.rows.push({id:uid(),cells:source?structuredClone(source.cells):{},created:new Date().toISOString()});}
  if(action==='remove-row')data.rows=data.rows.filter(r=>r.id!==id);
  render();persist();
 });
 host.addEventListener('input',e=>{const t=e.target;if(!t.dataset.row||t.tagName!=='INPUT'||t.type==='checkbox')return;const row=data.rows.find(r=>r.id===t.dataset.row),c=data.columns.find(c=>c.id===t.dataset.col);row.cells[c.id]=c.type==='number'?(t.value===''?'':Number(t.value)):c.type==='multi'?t.value.split(',').map(s=>s.trim()).filter(Boolean):t.value;row.updated=new Date().toISOString();for(const output of host.querySelectorAll('[data-computed-row]')){const r=data.rows.find(r=>r.id===output.dataset.computedRow),col=data.columns.find(c=>c.id===output.dataset.computedCol);output.textContent=String(cellValue(r,col,data));}clearTimeout(saveTimer);generation++;unsettled.add(host);status('저장 대기');saveTimer=setTimeout(persist,650);});
 render();return {flush:()=>{if(unsettled.has(host))persist();return tail;},get:()=>JSON.stringify(data)};
}
