export const propertyTypes={text:'텍스트',number:'숫자',select:'선택',multi:'다중 선택',date:'날짜',checkbox:'체크',url:'URL',relation:'기록 연결',formula:'수식',rollup:'연결 개수'};
export function newDatabase(){return {version:1,columns:[{id:'title',name:'이름',type:'text'},{id:'status',name:'상태',type:'select',options:['시작 전','진행 중','완료']},{id:'date',name:'날짜',type:'date'}],rows:[],view:'table',filter:'',sort:'title',descending:false,group:'status',date:'date'};}
export function parseDatabase(text){const d=typeof text==='string'?JSON.parse(text):text;if(!d||d.version!==1||!Array.isArray(d.columns)||!d.columns.length||d.columns.length>60||!Array.isArray(d.rows)||d.rows.length>10000)throw Error('데이터베이스 형식을 확인하세요.');const validId=id=>typeof id==='string'&&/^[a-zA-Z0-9_-]{1,128}$/.test(id)&&!['__proto__','prototype','constructor'].includes(id);const ids=new Set();for(const c of d.columns){if(!c||!validId(c.id)||ids.has(c.id)||typeof c.name!=='string'||!Object.hasOwn(propertyTypes,c.type)||(c.options!==undefined&&(!Array.isArray(c.options)||c.options.length>300||!c.options.every(x=>typeof x==='string')))||(c.expression!==undefined&&typeof c.expression!=='string')||(c.source!==undefined&&typeof c.source!=='string'))throw Error('속성이 손상되었습니다.');ids.add(c.id);}const rows=new Set();for(const r of d.rows){if(!r||!validId(r.id)||rows.has(r.id)||!r.cells||typeof r.cells!=='object'||Array.isArray(r.cells)||!Object.entries(r.cells).every(([k,v])=>validId(k)&&(typeof v==='string'||typeof v==='boolean'||typeof v==='number'&&Number.isFinite(v)||Array.isArray(v)&&v.every(x=>typeof x==='string'))))throw Error('행이 손상되었습니다.');rows.add(r.id);}return d;}
// A deliberately small arithmetic parser; never evaluate user text as JavaScript.
export function formulaValue(expression,cells,columns){
 const source=String(expression||'').replace(/\[([^\]]+)\]/g,(_,name)=>{const c=columns.find(c=>c.name===name||c.id===name);const value=Number(cells[c?.id]??0);if(!Number.isFinite(value))throw Error('숫자가 아닌 속성');return String(value);});
 const tokens=source.match(/\d+(?:\.\d+)?|[()+\-*/]/g)||[];if(tokens.join('')!==source.replace(/\s/g,''))throw Error('수식은 숫자, [속성], + - * / ( )를 사용하세요.');let i=0;
 const atom=()=>{const t=tokens[i++];if(t==='-')return -atom();if(t==='+')return atom();if(t==='('){const n=sum();if(tokens[i++]!==')')throw Error('괄호를 확인하세요.');return n;}if(!/^\d/.test(t||''))throw Error('수식이 비어 있거나 불완전합니다.');return Number(t);};
 const product=()=>{let n=atom();while(tokens[i]==='*'||tokens[i]==='/'){const op=tokens[i++],r=atom();n=op==='*'?n*r:n/r;}return n;};
 const sum=()=>{let n=product();while(tokens[i]==='+'||tokens[i]==='-'){const op=tokens[i++],r=product();n=op==='+'?n+r:n-r;}return n;};
 const n=sum();if(i!==tokens.length||!Number.isFinite(n))throw Error('계산할 수 없는 수식');return n;
}
export function cellValue(row,column,database){if(column.type==='formula'){try{return formulaValue(column.expression,row.cells,database.columns);}catch{return '수식 오류';}}if(column.type==='rollup'){const v=row.cells[column.source];return Array.isArray(v)?v.length:v?1:0;}return row.cells[column.id]??'';}
export function visibleRows(d){const key=String(d.filter||'').toLocaleLowerCase(),column=d.columns.find(c=>c.id===d.sort);return d.rows.filter(r=>!key||d.columns.some(c=>String(cellValue(r,c,d)).toLocaleLowerCase().includes(key))).slice().sort((a,b)=>{if(!column)return 0;const x=cellValue(a,column,d),y=cellValue(b,column,d);return (typeof x==='number'&&typeof y==='number'?x-y:String(x).localeCompare(String(y),'ko',{numeric:true}))*(d.descending?-1:1);});}
export function databaseCSV(d){const quote=v=>'"'+String(v??'').replaceAll('"','""')+'"';return '\uFEFF'+[d.columns.map(c=>quote(c.name)).join(','),...visibleRows(d).map(r=>d.columns.map(c=>quote(cellValue(r,c,d))).join(','))].join('\r\n');}
export function parseCSV(source){const rows=[];let row=[],cell='',quoted=false;source=source.replace(/^\uFEFF/,'');for(let i=0;i<source.length;i++){const c=source[i];if(c==='"'){if(quoted&&source[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&source[i+1]==='\n')i++;row.push(cell);rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('CSV의 따옴표가 닫히지 않았습니다.');if(cell||row.length){row.push(cell);rows.push(row);}return rows;}
export function databaseMarkdown(text){if(!text)return '';const d=parseDatabase(text),escape=v=>String(v??'').replaceAll('|','\\|').replace(/\r?\n/g,' ');return '\n\n## 데이터베이스\n\n| '+d.columns.map(c=>escape(c.name)).join(' | ')+' |\n| '+d.columns.map(()=>'---').join(' | ')+' |\n'+d.rows.map(r=>'| '+d.columns.map(c=>escape(cellValue(r,c,d))).join(' | ')+' |').join('\n');}
