import {esc,validateBackup} from './core.js';
import {documentAssetReferences} from './document-pages-model.js';
import {stable,digest,captureLocal,mergeRecords,validateSyncEnvelope} from './sync-model.js';
let googleScript;
function loadGoogle(){return googleScript??=new Promise((resolve,reject)=>{if(globalThis.google?.accounts){resolve();return;}const s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.onload=resolve;s.onerror=()=>{googleScript=null;reject(Error('구글 로그인 도구를 불러오지 못했습니다.'));};document.head.append(s);});}
export function setupDriveSync(api){
 const {db,toast,changed,flush,busy,demo}=api;let token='',expires=0,running=false,timer,account='',device='',config={},status='연결 안 됨',fileId='',controller;
 const setStatus=text=>{status=text;document.querySelectorAll('[data-cloud-status]').forEach(el=>el.textContent=text);};
 // 클라이언트 ID가 없으면 동기화를 쓸 수 없으므로 왼쪽 아래 상태 줄을 숨긴다(설정 창의 항목은 남긴다).
 const configured=()=>/^[a-zA-Z0-9_-]+\.apps\.googleusercontent\.com$/.test(config.clientId||'');
 const showEntry=()=>document.querySelectorAll('[data-cloud-entry]').forEach(el=>el.hidden=!configured());
 const request=async(url,options={})=>{if(!token||Date.now()>=expires){token='';setStatus('구글 재연결 필요');throw Error('구글 로그인을 다시 연결해 주세요.');}const r=await fetch(url,{...options,headers:{...options.headers,Authorization:'Bearer '+token},signal:controller?.signal});if(!r.ok){if(r.status===401){token='';setStatus('구글 재연결 필요');}throw Error('구글 드라이브 요청 실패 ('+r.status+')');}return r;};
 const init=(async()=>{config=(await db.get('meta','cloud-config'))?.value||{};if(!config.clientId){try{const shared=await(await fetch('./cloud-config.json')).json();config.clientId=shared.googleClientId||'';}catch{}}device=config.device||crypto.randomUUID();showEntry();})();
 async function connect(){await init;if(demo)throw Error('체험 서재는 동기화하지 않습니다.');if(!/^[a-zA-Z0-9_-]+\.apps\.googleusercontent\.com$/.test(config.clientId||''))throw Error('먼저 Google OAuth 클라이언트 ID를 설정해 주세요.');await loadGoogle();const reply=await new Promise((resolve,reject)=>{const client=google.accounts.oauth2.initTokenClient({client_id:config.clientId,scope:'https://www.googleapis.com/auth/drive.appdata https://www.googleapis.com/auth/drive.file',callback:r=>r.error?reject(Error(r.error)):resolve(r),error_callback:()=>reject(Error('구글 로그인 창이 닫혔거나 차단되었습니다.'))});client.requestAccessToken({prompt:''});});token=reply.access_token;expires=Date.now()+(Number(reply.expires_in)-60)*1000;const about=await (await request('https://www.googleapis.com/drive/v3/about?fields=user(permissionId,emailAddress)')).json();account=about.user.permissionId;fileId='';setStatus('연결됨 · '+about.user.emailAddress);await synchronize();}
 async function synchronize(){if(navigator.locks)return navigator.locks.request('pkos-cloud-sync',{ifAvailable:true},lock=>lock?runSync():undefined);return runSync();}
 async function runSync(){if(running||demo||!token||!navigator.onLine)return;if(busy()){setStatus('편집 완료 후 동기화');return;}running=true;controller=new AbortController();try{if(!await flush())return;setStatus('동기화 중');const previous=(await db.get('meta','cloud-state-'+account))?.value||{};const backup=await db.backup();if(JSON.stringify(backup).length>75*1024*1024)throw Error('동기화 자료가 75MB를 넘었습니다. 큰 첨부를 별도로 보관해 주세요.');const local=captureLocal(backup.notes,previous.records,device);let page='',files=[];do{const listing=await (await request('https://www.googleapis.com/drive/v3/files?spaces=appDataFolder&pageSize=100&fields=nextPageToken,files(id,name,md5Checksum)&q='+encodeURIComponent("trashed = false and name contains 'pkos-sync-v1-'")+(page?'&pageToken='+encodeURIComponent(page):''))).json();files.push(...listing.files);page=listing.nextPageToken;}while(page);if(files.length>100)throw Error('연결 기기가 너무 많습니다. 동기화 파일을 확인해 주세요.');const remotes=[];
 for(const file of files){if(file.name==='pkos-sync-v1-'+device+'.json')fileId=file.id;if(file.md5Checksum&&previous.remoteVersions?.[file.id]===file.md5Checksum)continue;const response=await request('https://www.googleapis.com/drive/v3/files/'+encodeURIComponent(file.id)+'?alt=media');const text=await response.text();if(text.length>80*1024*1024)throw Error('원격 동기화 파일이 허용 크기를 넘었습니다.');const envelope=validateSyncEnvelope(JSON.parse(text));validateBackup({format:'pkem-backup',schema:1,notes:Object.values(envelope.records).map(r=>r.note).filter(Boolean),assets:envelope.assets,folders:envelope.folders});remotes.push(envelope);if(envelope.device===device)fileId=file.id;}
 const merged=await mergeRecords([local,...remotes.map(x=>x.records)]),assets=new Map();for(const a of [...backup.assets,...remotes.flatMap(x=>x.assets)]){const existing=assets.get(a.id);if(existing&&stable(existing)!==stable(a))throw Error('같은 첨부 ID의 원본이 서로 달라 동기화를 중지했습니다. 원본은 양쪽에 남아 있습니다.');assets.set(a.id,a);}const needed=new Set(Object.values(merged.records).flatMap(r=>r.note?documentAssetReferences(r.note):[]));const payload={format:'pkos-sync',version:1,device,records:merged.records,assets:[...assets.values()].filter(a=>needed.has(a.id)),folders:[...new Set([...backup.folders,...remotes.flatMap(x=>x.folders)])]};const body=JSON.stringify(payload);if(body.length>80*1024*1024)throw Error('합친 동기화 자료가 80MB를 넘었습니다.');
 const uploadHash=await digest(payload);const uploaded=uploadHash!==previous.uploadHash;
 if(uploaded&&fileId)await request('https://www.googleapis.com/upload/drive/v3/files/'+encodeURIComponent(fileId)+'?uploadType=media',{method:'PATCH',headers:{'Content-Type':'application/json'},body});else if(uploaded){const boundary='pkos_'+crypto.randomUUID(),meta=JSON.stringify({name:'pkos-sync-v1-'+device+'.json',parents:['appDataFolder']});const created=await (await request('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id',{method:'POST',headers:{'Content-Type':'multipart/related; boundary='+boundary},body:'--'+boundary+'\r\nContent-Type: application/json\r\n\r\n'+meta+'\r\n--'+boundary+'\r\nContent-Type: application/json\r\n\r\n'+body+'\r\n--'+boundary+'--'})).json();fileId=created.id;}
 if(busy())throw Error('편집 중인 내용을 보호하기 위해 합치기를 미뤘습니다. 편집을 마치면 다시 동기화합니다.');const remoteChanged=stable(previous.records)!==stable(payload.records)||stable(backup.folders)!==stable(payload.folders);if(remoteChanged)await db.applyCloudSnapshot(backup.notes,payload,'cloud-state-'+account);await db.put('meta',{id:'cloud-state-'+account,value:{records:payload.records,uploadHash,remoteVersions:Object.fromEntries(files.filter(f=>f.md5Checksum).map(f=>[f.id,f.md5Checksum]))}});if(remoteChanged)await changed();setStatus('동기화됨 · '+new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'}));if(merged.conflicts.length)toast('동시에 수정된 글 '+merged.conflicts.length+'개를 충돌 사본으로 보관했습니다.');
 }catch(e){if(e.name!=='AbortError'){setStatus('동기화 확인 필요');toast(e.message);}}finally{running=false;controller=null;}}
 function schedule(){clearTimeout(timer);if(token)timer=setTimeout(synchronize,2500);}
 window.addEventListener('pkos-store-change',schedule);window.addEventListener('online',schedule);document.addEventListener('visibilitychange',()=>{if(!document.hidden)schedule();});setInterval(()=>{if(!document.hidden&&token)synchronize();},60000);
 async function show(){await init;const d=api.dialog('PC · 휴대폰 동기화',`<p>두 기기에서 같은 구글 계정을 연결하면 기록과 첨부를 자동으로 합칩니다. 서재가 열려 있을 때 저장 후·1분마다 확인합니다. 편집 중인 글은 읽기 화면으로 나가면 동기화합니다. 동시에 고친 글은 충돌 사본으로 보관합니다.</p><p data-cloud-status role="status">${esc(status)}</p><label>Google OAuth 클라이언트 ID<input id="cloud-client" value="${esc(config.clientId||'')}" placeholder="…apps.googleusercontent.com"></label><p class="hint">클라이언트 ID는 비밀번호가 아닙니다. Google Cloud에서 Drive API를 켜고 웹 클라이언트를 만든 뒤 사용 주소를 승인된 JavaScript 원본에 등록합니다. <a href="cloud-setup.html" target="_blank" rel="noopener">연결 설정 안내</a></p><p class="hint">로그인 토큰은 메모리에만 보관합니다. 브라우저를 다시 열거나 토큰이 만료되면 재연결이 필요합니다. 연결 해제는 구글의 저장 자료를 삭제하지 않습니다. 첫 연결은 이 기기의 기록도 같은 계정 서재에 합칩니다.</p><button type="button" id="cloud-connect">설정 저장 · 구글 연결</button><button type="button" id="cloud-now">지금 동기화</button><button type="button" id="cloud-disconnect">연결 해제</button>`);d.querySelector('#cloud-connect').onclick=async()=>{try{config={clientId:d.querySelector('#cloud-client').value.trim(),device};await db.put('meta',{id:'cloud-config',value:config});showEntry();await connect();}catch(e){toast(e.message);}};d.querySelector('#cloud-now').onclick=()=>synchronize();d.querySelector('#cloud-disconnect').onclick=()=>{controller?.abort();if(token)google.accounts.oauth2.revoke(token,()=>{});token='';setStatus('연결 안 됨');};}
 async function convertPpt(asset,signal){if(!token||Date.now()>=expires)throw Error('설정에서 구글 드라이브를 먼저 연결해 주세요.');const boundary='pkos_'+crypto.randomUUID(),metadata={name:'PKOS 변환 - '+asset.name,mimeType:'application/vnd.google-apps.presentation'};const body=new Blob(['--'+boundary+'\r\nContent-Type: application/json\r\n\r\n'+JSON.stringify(metadata)+'\r\n--'+boundary+'\r\nContent-Type: application/vnd.ms-powerpoint\r\n\r\n',asset.blob,'\r\n--'+boundary+'--']);const r=await request('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id',{method:'POST',headers:{'Content-Type':'multipart/related; boundary='+boundary},body});const {id}=await r.json();try{if(signal?.aborted)throw new DOMException('취소','AbortError');return await (await request('https://www.googleapis.com/drive/v3/files/'+id+'/export?mimeType=application%2Fpdf')).blob();}finally{await request('https://www.googleapis.com/drive/v3/files/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({trashed:true})}).catch(()=>toast('변환용 구글 슬라이드가 내 드라이브에 남았습니다. 직접 정리할 수 있습니다.'));}}
 return {show,synchronize,convertPpt,configured,status:()=>status};
}
