import {launchBrowser} from './browser-runtime.mjs';import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';
const browser=await launchBrowser(),page=await browser.newPage({viewport:{width:1200,height:1000},acceptDownloads:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));
try{await page.addInitScript(()=>localStorage.setItem('pkos-guide-v1','done'));await page.goto('http://127.0.0.1:8898/');await page.locator('[data-action="database-new"]').click();
 async function addColumn(name,type,expression=''){await page.locator('[data-db="column"]').click();const d=page.locator('.database-property-dialog');await d.locator('[name=name]').fill(name);await d.locator('[name=type]').selectOption(type);if(expression)await d.locator('[name=expression]').fill(expression);await d.getByRole('button',{name:'저장',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[data-db-status]')?.textContent==='저장됨');}
 await addColumn('수량','number');await addColumn('단가','number');await addColumn('총액','formula','[수량] * [단가]');await addColumn('참고','relation');
 await page.locator('[data-db="add"]').click();await page.getByRole('textbox',{name:'이름',exact:true}).fill('수업 준비');await page.getByRole('spinbutton',{name:'수량',exact:true}).fill('3');await page.getByRole('spinbutton',{name:'단가',exact:true}).fill('1200');await page.getByRole('spinbutton',{name:'단가',exact:true}).press('Tab');await page.waitForFunction(()=>document.querySelector('.db-scroll output')?.textContent==='3600');
 await page.locator('[data-db="relation"]').click();await page.locator('[data-options] input').first().check();await page.getByRole('button',{name:'연결 저장',exact:true}).click();assert.ok((await page.locator('[data-db="relation"]').innerText()).includes('데이터베이스'));
 const currentMonth=new Date().toISOString().slice(0,7);await page.locator('[data-col=date]').fill(currentMonth+'-10');await page.locator('[data-col=date]').press('Tab');await page.locator('[data-db-setting=view]').selectOption('calendar');assert.equal(await page.locator('.db-month [data-db=row-detail]').count(),1);await page.locator('[data-db=month-next]').click();assert.equal(await page.locator('.db-month [data-db=row-detail]').count(),0);await page.locator('[data-db=month-prev]').click();await page.locator('.db-month [data-db=row-detail]').click();assert.equal(await page.locator('[data-db-setting=view]').inputValue(),'list');
 const downloads=page.waitForEvent('download');await page.locator('[data-db=csv]').click();const download=await downloads;assert.ok(download.suggestedFilename().endsWith('.csv'));
 await page.reload();await page.waitForSelector('#note-database');assert.equal(await page.getByRole('spinbutton',{name:'단가',exact:true}).inputValue(),'1200');
 const exports=await page.evaluate(async()=>{const {openStore}=await import('/store.js'),{validateBackup,markdownFile}=await import('/core.js'),{buildReadingBundle}=await import('/reading-export.js');const db=await openStore(),data=await db.backup();validateBackup(data);const n=data.notes.find(n=>n.database);return {markdown:markdownFile(n,data.notes,[]),backup:JSON.parse(n.database),reading:!!(await buildReadingBundle([n],[]))};});assert.match(exports.markdown,/수업 준비/);assert.match(exports.markdown,/3600/);assert.ok(exports.reading);assert.equal(exports.backup.rows.length,1);assert.deepEqual(errors,[]);await page.screenshot({path:'tests/database-desktop.png',fullPage:true});await writeFile('tests/database-result.json',JSON.stringify({formula:true,relation:true,calendar:true,csv:true,backup:true,markdown:true,reading:true,errors},null,2));console.log('PASS database: properties, arithmetic, record relation, actual monthly calendar, persistence and exports');
}catch(e){console.log(await page.locator('#note-database').innerText());console.log(await page.locator('#note-database input').evaluateAll(es=>es.map(e=>({label:e.getAttribute('aria-label'),value:e.value}))));await page.screenshot({path:'tests/database-failure.png'});throw e;}finally{await browser.close();}
