import {launchBrowser} from './browser-runtime.mjs';
import fs from 'node:fs/promises';
import {unzipSync,strFromU8} from '../vendor/fflate.js';
const browser=await launchBrowser(),results=[],baseURL=process.env.PKOS_TEST_URL||'http://127.0.0.1:8793/';
const assert=(x,m)=>{if(!x)throw Error(m);};
const check=(name)=>{results.push(name);console.log('PASS '+name);};
let context;
try{
 context=await browser.newContext({viewport:{width:1440,height:960},acceptDownloads:true});
 await context.addInitScript(()=>{
  localStorage.setItem('pkos-guide-v1','done');localStorage.setItem('pkos-folder-guide-v1','done');window.testStreams=[];window.testSpeechStarts=0;
  navigator.mediaDevices.getUserMedia=async options=>{
   if(window.denyDevice)throw new DOMException('denied','NotAllowedError');
   let stream;
   if(options.video){const c=document.createElement('canvas');c.width=640;c.height=480;const g=c.getContext('2d');g.fillStyle='#6354a4';g.fillRect(0,0,640,480);g.fillStyle='#ffffff';g.fillRect(60,60,240,160);stream=c.captureStream(10);}
   else{const a=new AudioContext();await a.resume();const osc=a.createOscillator(),out=a.createMediaStreamDestination();osc.connect(out);osc.start();stream=out.stream;window.testAudio=a;}
   window.testStreams.push(stream);return stream;
  };
  class FakeSpeech{
   start(){window.testSpeechStarts++;setTimeout(()=>{this.onstart?.();const result=[{transcript:'가상 음성 인식 결과'}];result.isFinal=true;this.onresult?.({resultIndex:0,results:[result]});this.onresult?.({resultIndex:0,results:[result]});},20);}
   stop(){setTimeout(()=>this.onend?.(),0);}
   abort(){this.onend?.();}
  }
  window.SpeechRecognition=FakeSpeech;
 });
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.goto(baseURL);await page.locator('[data-action="new"]:visible').first().click();await page.locator('#edit-title').fill('입력 도구 통합 검증');
 const body=page.locator('#edit-body');await body.fill('/표');await page.locator('#editor-command-menu:not([hidden])').waitFor();await body.press('Enter');assert((await body.inputValue()).includes('| 항목 | 내용 |'),'table command');check('slash Korean search and table insertion');
 await body.fill('/없는명령');assert(await page.locator('#editor-command-menu').innerText().then(x=>x.includes('일치하는 명령')),'no matches');await body.press('Escape');await body.fill('남겨 둘 원문\n');
 await page.locator('[data-editor-tool="commands"]').click();assert(await page.locator('[role="option"]').count()===25,'25 commands');await body.press('Escape');check('toolbar menu and no-match/escape');
 await body.evaluate(e=>e.dispatchEvent(new CompositionEvent('compositionstart')));await body.fill('/');assert(await page.locator('#editor-command-menu').isHidden(),'IME menu hidden');await body.evaluate(e=>e.dispatchEvent(new CompositionEvent('compositionend')));await body.press('Escape');await body.fill('남겨 둘 원문\n');check('IME composition does not execute commands');
 await page.locator('[data-editor-tool="camera"]').click();await page.locator('[data-capture="camera-start"]').click();await page.locator('video.camera-live').waitFor();await page.waitForFunction(()=>document.querySelector('video.camera-live')?.videoWidth>0);await page.locator('[data-capture="shot"]').click();await page.locator('.camera-result:not([hidden])').waitFor();
 assert(await page.evaluate(()=>testStreams.every(s=>s.getTracks().every(t=>t.readyState==='ended'))),'camera released');
 // Exercise storage failure without modifying any existing user data.
 await page.evaluate(()=>{window.originalTransaction=IDBDatabase.prototype.transaction;IDBDatabase.prototype.transaction=function(names,mode,...args){if(mode==='readwrite'&&Array.isArray(names)&&names.includes('assets'))throw new DOMException('시험 용량 부족','QuotaExceededError');return originalTransaction.call(this,names,mode,...args);};});
 await page.locator('[data-capture="save"]').click();await page.waitForFunction(()=>document.querySelector('.capture-status')?.textContent.includes('저장 실패'));assert(await page.locator('.camera-result').isVisible(),'photo retained after failure');
 await page.evaluate(()=>IDBDatabase.prototype.transaction=originalTransaction);await page.locator('[data-capture="save"]').click();await page.locator('.capture-dialog').waitFor({state:'detached'});check('camera JPEG capture, track cleanup, failure retention and retry');
 await page.locator('[data-editor-tool="record"]').click();assert(await page.locator('#speech-consent').isChecked(),'recording dictation defaults on');assert(await page.evaluate(()=>testSpeechStarts)===0,'opening recording does not start speech');await page.locator('[data-capture="record-start"]').click();await page.locator('[data-capture="pause"]').waitFor();await page.waitForTimeout(3200);await page.locator('[data-capture="pause"]').click();assert(await page.locator('[data-capture="pause"]').innerText()==='녹음 계속','pause');await page.locator('[data-capture="pause"]').click();await page.waitForTimeout(300);await page.locator('[data-capture="stop"]').click();await page.locator('.record-result:not([hidden])').waitFor();
 await page.locator('.record-result').evaluate(async e=>{await e.play();e.pause();});
 assert(await page.evaluate(()=>testStreams.every(s=>s.getTracks().every(t=>t.readyState==='ended'))),'microphone released');
 await page.locator('[data-capture="save"]').click();await page.locator('.capture-dialog').waitFor({state:'detached'});check('real MediaRecorder with synthetic sound: pause, resume, playback, save');
 await page.locator('[data-editor-tool="dictate"]').click();assert(await page.locator('#speech-consent').isChecked(),'dictation defaults on');assert(await page.evaluate(()=>testSpeechStarts)===0,'opening dictation does not start speech');await page.locator('#speech-consent').uncheck();await page.locator('[data-capture="speech"]').click();assert(await page.evaluate(()=>testSpeechStarts)===0,'unchecked service never starts speech');assert(await page.locator('.capture-status').innerText().then(x=>x.includes('체크')),'consent required');await page.locator('#speech-consent').check();await page.locator('[data-capture="speech"]').click();await page.waitForFunction(()=>document.querySelector('.transcript')?.value==='가상 음성 인식 결과');assert(await page.evaluate(()=>testSpeechStarts)===1,'speech starts only after explicit start');await page.locator('[data-capture="speech-stop"]').click();await page.locator('.transcript').fill('수정한 받아쓰기 결과');await page.locator('[data-capture="save"]').click();await page.locator('.capture-dialog').waitFor({state:'detached'});assert((await body.inputValue()).includes('남겨 둘 원문')&&(await body.inputValue()).includes('수정한 받아쓰기 결과'),'append transcript');check('speech simulation: enabled default, manual start, opt-out, deduplication, stop and editable transcript');
 await page.locator('.doc-actions [data-action="save"]').click();await page.locator('.attachments img').waitFor();await page.locator('.attachments audio').waitFor();await page.reload();await page.locator('.prose').filter({hasText:'수정한 받아쓰기 결과'}).waitFor();assert(await page.locator('.attachment-card').count()===2,'saved two attachments');check('photo, sound and transcript survive reload');
 const backup=await page.evaluate(async()=>{const {openStore}=await import('./store.js');return (await openStore(false)).backup();});assert(backup.assets.length===2&&backup.assets.every(a=>a.data.length>100),'backup bytes');
 const other=await browser.newContext();const restored=await other.newPage();await restored.addInitScript(()=>localStorage.setItem('pkos-guide-v1','done'));await restored.goto(baseURL);const roundtrip=await restored.evaluate(async data=>{const {openStore}=await import('./store.js');const {validateBackup}=await import('./core.js');const db=await openStore(false);await db.mergeBackup(validateBackup(data));return db.backup();},backup);assert(JSON.stringify(roundtrip.assets)===JSON.stringify(backup.assets),'backup asset bytes exact');assert(roundtrip.notes[0].body===backup.notes[0].body,'transcript restore');await restored.reload();await restored.locator('.attachments audio').waitFor();await other.close();check('backup validation and restore preserve exact media bytes and text');
 await page.locator('[data-action="settings"]:visible').first().click();const zipPromise=page.waitForEvent('download');await page.locator('[data-action="export-vault"]').click();const zipDownload=await zipPromise;const zip=unzipSync(new Uint8Array(await fs.readFile(await zipDownload.path())));assert(Object.keys(zip).filter(k=>k.startsWith('attachments/')).length===2,'zip attachment count');assert(Object.entries(zip).some(([k,b])=>k.endsWith('.md')&&strFromU8(b).includes('수정한 받아쓰기 결과')),'zip text');for(const a of backup.assets){const value=Object.entries(zip).find(([k])=>k.startsWith('attachments/'+a.id+'-'))?.[1];assert(value&&Buffer.from(value).toString('base64')===a.data,'zip exact bytes');}await page.locator('[data-action="dialog-close"]').click();check('Markdown ZIP includes exact originals and transcript');
 await page.locator('[data-action="edit"]:visible').click();await page.evaluate(()=>window.denyDevice=true);await page.locator('[data-editor-tool="camera"]').click();await page.locator('[data-capture="camera-start"]').click();await page.waitForFunction(()=>document.querySelector('.capture-status')?.textContent.includes('권한'));await page.locator('[data-capture="close"]').click();check('device permission denial is recoverable');
 await page.evaluate(()=>{window.SpeechRecognition=undefined;window.webkitSpeechRecognition=undefined;});await page.locator('[data-editor-tool="dictate"]').click();assert(await page.locator('[data-capture="speech"]').isDisabled(),'unsupported speech disabled');await page.locator('[data-capture="close"]').click();check('unsupported speech has clear fallback');
 for(const width of [390,320]){await page.setViewportSize({width,height:844});await page.locator('[data-editor-tool="commands"]').click();const valid=await page.locator('#editor-command-menu').evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth+1&&r.top>=0&&r.bottom<=innerHeight+1;});assert(valid,'mobile slash '+width);await body.press('Escape');await page.locator('[data-editor-tool="dictate"]').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile capture overflow');await page.locator('[data-capture="close"]').click();}check('320px and 390px command and capture layouts');
 assert(errors.length===0,errors.join('\n'));check('no uncaught browser errors');
 await page.setViewportSize({width:1440,height:960});await page.locator('[data-editor-tool="commands"]').click();await page.screenshot({path:'C:/Users/Public/Documents/ESTsoft/CreatorTemp/pkos-editor-tools.png'});
 await fs.writeFile('test-results/editor-tools.json',JSON.stringify({date:new Date().toISOString(),results,limits:['Devices use synthetic camera/audio streams. SpeechRecognition events are simulated. Real microphone, camera and online speech provider need user verification.']},null,2));
 console.log('ALL PASS '+results.length);
}finally{await context?.close();await browser.close();}

